# Generated by Django 5.2.4 on 2025-11-12 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_chatmessage_file'),
        ('workforce', '0008_event_postponed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('Crystal Sounds', 'Crystal Sounds'), ('Embassage', 'Embassage'), ('Expressions', 'Expressions'), ('Glitters', 'Glitters'), ('Green House', 'Green House'), ('Holy Police', 'Holy Police'), ('Magnet', 'Magnet'), ('Media', 'Media'), ('Royal Guards', 'Royal Guards'), ('Temple Keepers', 'Temple Keepers')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('Pastor', 'Pastor'), ('Minister', 'Minister'), ('GForce Member', 'GForce Member')], default='Team Member', max_length=30),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(choices=[('Minister-in-Charge', 'Minister-in-Charge'), ('Head of Unit', 'Head of Unit'), ('Asst. Head of Unit', 'Asst. Head of Unit'), ('Team Admin', 'Team Admin'), ('Subleader', 'Subleader'), ('Member', 'Member')], default='Member', max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workforce.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PersonalReminder',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
