# Generated by Django 5.2.4 on 2025-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='guest_card',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='pinned_by',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='seen_by',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='personalreminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        #migrations.DeleteModel(
        #    name='AttendanceRecord',
        #),
        #migrations.DeleteModel(
        #    name='ChatMessage',
        #),
        #migrations.DeleteModel(
        #    name='Event',
        #),
        #migrations.DeleteModel(
        #    name='PersonalReminder',
        #),
        #migrations.DeleteModel(
        #    name='UserActivity',
        #),
    ]
