# Generated by Django 5.2.4 on 2025-10-23 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_chatmessage_guest_card_and_more'),
        ('workforce', '0002_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('Pastor', 'Pastor'), ('Minister', 'Minister'), ('Team Member', 'Team Member')], default='Team Member', max_length=30),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(choices=[('Minister-in-Charge', 'Minister-in-Charge'), ('Head of Unit', 'Head of Unit'), ('Asst. Head of Unit', 'Asst. Head of Unit'), ('Team Admin', 'Team Admin'), ('Subleader', 'Subleader'), ('Member', 'Member')], default='Member', max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workforce.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'team')},
            },
        ),
    ]
