# Generated by Django 5.2.4 on 2025-10-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_migrate_team_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('Crystal Sounds', 'Crystal Sounds'), ('Embassage', 'Embassage'), ('Expressions', 'Expressions'), ('Glitters', 'Glitters'), ('Green House', 'Green House'), ('Holy Police', 'Holy Police'), ('Magnet', 'Magnet'), ('Media', 'Media'), ('Royal Guards', 'Royal Guards'), ('Temple Keepers', 'Temple Keepers')], max_length=255, null=True),
        ),
    ]
