# Generated by Django 5.2.4 on 2025-10-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('Pastor', 'Pastor'), ('Minister', 'Minister'), ('GForce Member', 'GForce Member')], default='Team Member', max_length=30),
        ),
    ]
