# Generated by Django 5.2.4 on 2025-11-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_customuser_role'),
    ]

    operations = [
    ]
