# Generated by Django 5.2.4 on 2025-11-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_sync_current_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='PersonalReminder',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
