# Generated by Django 5.2.4 on 2025-11-01 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='team',
            field=models.ForeignKey(blank=True, help_text='If event is team-specific, store which team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='workforce.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Leave blank for general church-wide events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='workforce.team'),
        ),
    ]
