# Generated by Django 5.2.4 on 2025-11-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_attendancerecord_team_event_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
