# Generated by Django 5.2.4 on 2025-11-04 01:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_remove_attendancerecord_clock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_image'),
        ),
    ]
