# Generated by Django 5.2.4 on 2025-11-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
        migrations.AddField(
            model_name='event',
            name='registrable',
            field=models.BooleanField(default=False, help_text='If True, allows users to register for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='URL to the event registration page', max_length=500, null=True),
        ),
    ]
