# Generated by Django 5.2.4 on 2025-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_remove_team_color_event_registrable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
    ]
