# Generated by Django 5.2.4 on 2025-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_event_postponed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
