# Generated by Django 5.2.4 on 2025-11-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_alter_chatmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='link_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
