# Generated by Django 5.2.4 on 2025-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0011_alter_chatmessage_file_alter_chatmessage_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
