# Generated by Django 5.2.4 on 2025-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0014_alter_chatmessage_file_alter_chatmessage_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='link_image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='link_url',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
