# Generated by Django 5.2.4 on 2025-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0015_alter_chatmessage_link_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='link_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
